#+title: VoxStack Details

* Inputs
Data sourced from [[https://talkbank.org/dementia/access/English/Pitt.html][DementiaBank Pitt Corpus]] (/not shareable/)
** Embedded transcripts
LLMs used for embeddings:
1. BAAI/bge-base-en-v1.5
2. BAAI/bge-m3
3. BAAI/bge-large-en-v1.5
4. bert-base-uncased
5. bert-large-uncased
6. bert-large-uncased
7. roberta-base
8. roberta-large
VoxStack model was trained on each of the embedding types separately.
** 88 audio features generated by [[https://audeering.github.io/opensmile-python/][openSMILE]] - [[https://sail.usc.edu/publications/files/eyben-preprinttaffc-2015.pdf][eGeMAPS feature set]]
** 5 quantitative features:
1. Duration of the utterance
2. Letters per utterance
3. Words per utterance
4. Count of [[https://talkbank.org/0info/manuals/CHAT.pdf#page=46][phonological fragments]]
   1. Count of [[https://talkbank.org/0info/manuals/CHAT.pdf#page=46][fillers]]
* Where to look for results
** =data/train_res.log= contains average AUC and F1 scores of VoxStack model trained on embeddings of different LLMs (_averaged across 10 Fold Cross Validation_).
** =data/shap.log= contains average SHAP of VoxStack model trained on embeddings of different LLMs (_averaged across 10 Fold Cross Validation_).
** TODO plots generated by tensorboard from training logs
* Detailed code explanation
** =parser.py=:
- extracts utterances of the patients
- calculates quantitative features
- removes =.cha= related marks from the utterances
- extracts audio features of each utterance
- generates embeddings for each LLM type
** =utils.py=:
Various utilities used throught the code
** =train.py=:
Responsible for training the VoxStack model.
*** Model architecture:
#+begin_src python
class VoxStack(L.LightningModule):
    def __init__(
        self,
        embedding_dim,
        lr=5e-4,
        weight=None
    ):
        super().__init__()
        self.save_hyperparameters()

        self.quant_net = nn.Sequential(
            nn.Linear(5, 16),
            nn.BatchNorm1d(16),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(16, 8),
            nn.BatchNorm1d(8),
            nn.GELU(),
            nn.Dropout(0.8),
        )

        self.acoustic_net = nn.Sequential(
            nn.Linear(88, 128),
            nn.BatchNorm1d(128),
            nn.GELU(),
            nn.Dropout(0.5),
            nn.Linear(128, 64),
            nn.BatchNorm1d(64),
            nn.GELU(),
        )

        self.embedding_net = nn.Sequential(
            nn.Linear(embedding_dim, 256),
            nn.BatchNorm1d(256),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(256, 128),
            nn.BatchNorm1d(128),
            nn.GELU(),
            nn.Dropout(0.2),
        )

        self.classifier = nn.Sequential(
            nn.Linear(8 + 64 + 128, 64),
            nn.BatchNorm1d(64),
            nn.GELU(),
            nn.Dropout(0.3),
            nn.Linear(64, 1)
        )

        # Learnable branch weights (adjusted by optimizer)
        self.alpha_quant = nn.Parameter(torch.tensor(1.0))
        self.alpha_acoustic = nn.Parameter(torch.tensor(1.0))
        self.alpha_embedding = nn.Parameter(torch.tensor(1.0))

        if weight is not None:
            self.criterion = nn.BCEWithLogitsLoss(
                pos_weight=torch.tensor([weight])
            )
        else:
            self.criterion = nn.BCEWithLogitsLoss()

        self.train_auc = BinaryAUROC()
        self.val_auc = BinaryAUROC()
        self.val_f1 = BinaryF1Score()

    def forward(self, quant, acoustic, embedding):
        q = self.quant_net(quant)
        a = self.acoustic_net(acoustic)
        e = self.embedding_net(embedding)

        # add weights to branches (also  use softplus to avoid negative values)
        q_scaled = q * torch.nn.functional.softplus(self.alpha_quant)
        a_scaled = a * torch.nn.functional.softplus(self.alpha_acoustic)
        e_scaled = e * torch.nn.functional.softplus(self.alpha_embedding)

        fused = torch.cat([q_scaled, a_scaled, e_scaled], dim=1)
        logits = self.classifier(fused)
        return logits

    def training_step(self, batch, batch_idx):
        logits = self(
            batch["quant"],
            batch["acoustic"],
            batch["embedding"]
        )
        y = batch["label"]

        loss = self.criterion(logits.squeeze(1), y)

        probs = torch.sigmoid(logits).squeeze(1)

        self.log("train_loss", loss, prog_bar=True, on_epoch=True)
        self.train_auc.update(probs, y.int())
        self.log("train_auc", self.train_auc, prog_bar=True, on_epoch=True)

        return loss

    def validation_step(self, batch, batch_idx):
        logits = self(
            batch["quant"],
            batch["acoustic"],
            batch["embedding"]
        )
        y = batch["label"]

        loss = self.criterion(logits.squeeze(1), y)
        probs = torch.sigmoid(logits).squeeze(1)

        self.log("val_loss", loss, prog_bar=True, on_epoch=True)
        self.val_auc.update(probs, y.int())
        self.log("val_auc", self.val_auc, prog_bar=True, on_epoch=True)
        self.val_f1.update(probs, y.int())
        self.log("val_f1", self.val_f1, prog_bar=True, on_epoch=True)

    def configure_optimizers(self):
        optimizer = torch.optim.Adam(self.parameters(), lr=self.hparams.lr)

        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            optimizer,
            mode="max",
            factor=0.5,
            patience=2
        )

        return {
            "optimizer": optimizer,
            "lr_scheduler": {
                "scheduler": scheduler,
                "monitor": "val_auc"
            }
        }
#+end_src
**** Arch features
- The model has 3 branches - [[*Embedded transcripts.][Embeddings]], [[*88 audio features generated by \[\[https://audeering.github.io/opensmile-python/\]\[openSMILE\]\] - \[\[https://sail.usc.edu/publications/files/eyben-preprinttaffc-2015.pdf\]\[eGeMAPS feature set\]\]][Acoustic]], [[*5 quantitative features:][Quantitative]].
- Each branch is trained separtely and then passed to the final classifier
- Each branch has learnable weights (adjusted by [[*Optimizer: Adam][the optimizer]] during training)
- Trainer focuses on _maximizing AUC score_
- Each branch uses GELU, BranchNorm1d and extensive dropouts to make sure the model won't overfit
**** Optimizer: Adam
**** Initial learning rate: 5e-4
_Can be adjusted by the learning rate scheduler_
*** Training loop features:
- Attempts to maximize AUC score
- Early stopping on plateuing AUC score (patients = 5)
- Runs 10 fold crossvalidation (fold number is adjustable)
- Scales data using _StandardScaler_ to avoid branch dominance
- Checks for data leaks (prevents training if detected)
- Evaluates the best model across all the epochs for each fold
*** SHAP:
Nothing special. Just generates average SHAP stats across folds.
* Explanation of results
On average across 10 folds the best performing model of VoxStack is the one using embeddings from _BAAI/bge-m3_ (avg AUC=0.938, avg F1=0.812).
However, SHAP results show that embeddings don't matter as much as acoustic and quantitative features. Acoustic feature are almost 200 times more important than embeddings!
#+begin_quote
*Feature importance of Quantitative branch*:
utterance_times: 0.02341
phonological_frags_count: 0.00243
fillers_count: 0.00857
letters_per_utterance: 0.13222
words_per_utterance: 0.03132

*Feature importance of Acoustic branch*:
F0semitoneFrom27.5Hz_sma3nz_stddevRisingSlope: 2.53321
F3frequency_sma3nz_amean: 1.82868
F0semitoneFrom27.5Hz_sma3nz_stddevFallingSlope: 1.65494
F2frequency_sma3nz_amean: 1.13819
F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope: 0.84221
F1frequency_sma3nz_amean: 0.74120
F1bandwidth_sma3nz_amean: 0.72717
F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope: 0.64324
F3bandwidth_sma3nz_amean: 0.62601
F2bandwidth_sma3nz_amean: 0.61509

*Feature importance of Embeddings branch*:
emb_754: 0.00308
emb_640: 0.00293
emb_810: 0.00289
emb_1017: 0.00282
emb_65: 0.00263
emb_596: 0.00261
emb_964: 0.00254
emb_118: 0.00249
emb_80: 0.00244
emb_481: 0.00243

*Average importance across branches*:
Acoustic: 0.16606
Quantitative: 0.03959
Embedding: 0.00095
#+end_quote
